debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[web]
# Port for the status/dashboard page
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false